# Generated by Django 5.1.6 on 2025-03-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_сhapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
