# Generated by Django 5.1.6 on 2025-03-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_title_delete_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=255, verbose_name='Название')),
                ('source', models.CharField(default='Неизвестен', max_length=50, verbose_name='Источник')),
                ('release', models.DateField(verbose_name='Дата выпуска')),
                ('translator', models.CharField(default='Неизвестен', max_length=255, verbose_name='Переводчик')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'глава',
                'verbose_name_plural': 'Главы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет названия', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.DeleteModel(
            name='Сhapter',
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.AddField(
            model_name='title',
            name='author',
            field=models.CharField(default='Неизвестен', max_length=255, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='title',
            name='cover',
            field=models.URLField(default='', verbose_name='Полная обложка'),
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='Нет описания', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default='Нет названия', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='title',
            name='status',
            field=models.CharField(default='Неизвестен', max_length=127, verbose_name='Статус выхода'),
        ),
        migrations.AddField(
            model_name='title',
            name='thumbnail',
            field=models.URLField(default='', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='title',
            name='type',
            field=models.CharField(default='Неизвестен', max_length=127, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.CharField(default='0000', max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='titles.title'),
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(to='titles.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(to='titles.tag', verbose_name='Теги'),
        ),
    ]
