# Generated by Django 5.1.6 on 2025-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_chapter_genre_tag_delete_сhapter_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
