# Generated by Django 5.1.6 on 2025-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_title_mangalib_url_title_remanga_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
