# Generated by Django 5.1.6 on 2025-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_alter_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='mangalib_url',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ссылка на MangaLib'),
        ),
        migrations.AlterField(
            model_name='title',
            name='remanga_url',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ссылка на ReManga'),
        ),
    ]
