# Generated by Django 5.1.6 on 2025-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_alter_title_mangalib_url_alter_title_remanga_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='mangalib_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ссылка на MangaLib'),
        ),
        migrations.AlterField(
            model_name='title',
            name='remanga_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ссылка на ReManga'),
        ),
    ]
