# Generated by Django 5.1.6 on 2025-05-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0011_alter_title_mangalib_url_alter_title_remanga_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='mangalib_url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на MangaLib'),
        ),
    ]
